# Generated by Django 3.2.5 on 2022-03-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetail',
            old_name='user',
            new_name='name',
        ),
    ]
