# Generated by Django 3.2.5 on 2022-03-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_user_bankdetail_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpcode',
            old_name='otp',
            new_name='code',
        ),
    ]
